### ISSUE TITLE
It is a pain to set up and the instructions are vague 

### ISSUE THREAD

**Issue by SirSpudlington** [asiekierka/lunatic86#1]

**Comment by ghost** [comment]
same

**Comment by asiekierka** [comment]
I updated the instructions a little. Is this better?

**Comment by SirSpudlington** [comment]
Yes a lot better. thank you!

**Comment by Erokaution** [comment]
They're still a little unclear for me.
For example, trying to load up a freedos image by doing lunatic86 -a /mnt/f78/test.img alone is erroring out in that the program can't find any hard disks, and I'm pretty confused as to if I'm doing something wrong in how I'm using lunatic or if I'm using the wrong image.
